server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/employees/**,/api/departments/**
          filters:
            - StripPrefix=0
        - id: claim-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/claim-vouchers/**
          filters:
            - StripPrefix=0
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**,/api/logs/**
          filters:
            - StripPrefix=0
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

logging:
  level:
    org.springframework.cloud.gateway: debug
